// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: receive_msg.proto

package receive_msg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HandleReceiveMsgService_SendReceiveMsg_FullMethodName = "/receive_msg.HandleReceiveMsgService/SendReceiveMsg"
)

// HandleReceiveMsgServiceClient is the client API for HandleReceiveMsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HandleReceiveMsgServiceClient interface {
	SendReceiveMsg(ctx context.Context, in *ReplicaMsgRequest, opts ...grpc.CallOption) (*ReplicaMsgResponse, error)
}

type handleReceiveMsgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHandleReceiveMsgServiceClient(cc grpc.ClientConnInterface) HandleReceiveMsgServiceClient {
	return &handleReceiveMsgServiceClient{cc}
}

func (c *handleReceiveMsgServiceClient) SendReceiveMsg(ctx context.Context, in *ReplicaMsgRequest, opts ...grpc.CallOption) (*ReplicaMsgResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicaMsgResponse)
	err := c.cc.Invoke(ctx, HandleReceiveMsgService_SendReceiveMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandleReceiveMsgServiceServer is the server API for HandleReceiveMsgService service.
// All implementations must embed UnimplementedHandleReceiveMsgServiceServer
// for forward compatibility.
type HandleReceiveMsgServiceServer interface {
	SendReceiveMsg(context.Context, *ReplicaMsgRequest) (*ReplicaMsgResponse, error)
	mustEmbedUnimplementedHandleReceiveMsgServiceServer()
}

// UnimplementedHandleReceiveMsgServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHandleReceiveMsgServiceServer struct{}

func (UnimplementedHandleReceiveMsgServiceServer) SendReceiveMsg(context.Context, *ReplicaMsgRequest) (*ReplicaMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendReceiveMsg not implemented")
}
func (UnimplementedHandleReceiveMsgServiceServer) mustEmbedUnimplementedHandleReceiveMsgServiceServer() {
}
func (UnimplementedHandleReceiveMsgServiceServer) testEmbeddedByValue() {}

// UnsafeHandleReceiveMsgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandleReceiveMsgServiceServer will
// result in compilation errors.
type UnsafeHandleReceiveMsgServiceServer interface {
	mustEmbedUnimplementedHandleReceiveMsgServiceServer()
}

func RegisterHandleReceiveMsgServiceServer(s grpc.ServiceRegistrar, srv HandleReceiveMsgServiceServer) {
	// If the following call pancis, it indicates UnimplementedHandleReceiveMsgServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HandleReceiveMsgService_ServiceDesc, srv)
}

func _HandleReceiveMsgService_SendReceiveMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandleReceiveMsgServiceServer).SendReceiveMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandleReceiveMsgService_SendReceiveMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandleReceiveMsgServiceServer).SendReceiveMsg(ctx, req.(*ReplicaMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HandleReceiveMsgService_ServiceDesc is the grpc.ServiceDesc for HandleReceiveMsgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HandleReceiveMsgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "receive_msg.HandleReceiveMsgService",
	HandlerType: (*HandleReceiveMsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendReceiveMsg",
			Handler:    _HandleReceiveMsgService_SendReceiveMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "receive_msg.proto",
}
